name: Test Action CI

on: [push]

jobs:
  check:
    name: get data from gist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get data from gist
        uses: sergeysova/gist-read-action@master
        id: readed
        with:
          gist_id: e7213cee8029f2a76562feacedc3e3d4
          file_name: gist action test.txt
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: check if gist content not empty
        run: '[ "${{ steps.readed.outputs.content }}" ] || exit 1'

      - name: increment value from gist
        id: next
        run: echo "::set-output name=value::$((${{ steps.readed.outputs.content }} + 1))"

      - name: show incremented value ${{ steps.next.outputs.value }}
        run: echo ${{ steps.next.outputs.value }}
